#!/usr/bin/env bash
# Boosts kitty terminal colors generated by matugen to neon/vivid variants.
# Accent colors are pushed to high saturation and clamped to a lightness range
# that keeps them vivid without washing out to white. White/text roles are left
# at their natural lightness. Pure awk — no Python or extra deps needed.

KITTY_COLORS_FILE="/tmp/kitty-matugen-colors.conf"

[[ -f "$KITTY_COLORS_FILE" ]] || exit 0

awk '
# ---------------------------------------------------------------------------
# Hex helpers (POSIX awk — no strtonum)
# ---------------------------------------------------------------------------
function hex2dec(s,    i, c, v, digits) {
    v = 0; digits = "0123456789abcdef"; s = tolower(s)
    for (i = 1; i <= length(s); i++) {
        c = substr(s, i, 1)
        v = v * 16 + (index(digits, c) - 1)
    }
    return v
}
function hex_r(h) { return hex2dec(substr(h, 2, 2)) / 255 }
function hex_g(h) { return hex2dec(substr(h, 4, 2)) / 255 }
function hex_b(h) { return hex2dec(substr(h, 6, 2)) / 255 }

# ---------------------------------------------------------------------------
# RGB -> HLS
# ---------------------------------------------------------------------------
function max3(a,b,c) { return (a>b ? (a>c?a:c) : (b>c?b:c)) }
function min3(a,b,c) { return (a<b ? (a<c?a:c) : (b<c?b:c)) }

function rgb_h(r,g,b,    mx,mn,d,h) {
    mx=max3(r,g,b); mn=min3(r,g,b); d=mx-mn
    if (d == 0) return 0
    if      (mx == r) { h = (g-b)/d; if (g < b) h += 6 }
    else if (mx == g) { h = (b-r)/d + 2 }
    else              { h = (r-g)/d + 4 }
    return h / 6
}
function rgb_l(r,g,b) { return (max3(r,g,b) + min3(r,g,b)) / 2 }
function rgb_s(r,g,b,    mx,mn,l,d) {
    mx=max3(r,g,b); mn=min3(r,g,b); d=mx-mn; l=(mx+mn)/2
    if (d == 0) return 0
    return (l < 0.5) ? d/(mx+mn) : d/(2-mx-mn)
}

# ---------------------------------------------------------------------------
# HLS -> RGB
# ---------------------------------------------------------------------------
function _hue(p,q,t) {
    if (t < 0) t += 1; if (t > 1) t -= 1
    if (t < 1/6) return p + (q-p)*6*t
    if (t < 0.5) return q
    if (t < 2/3) return p + (q-p)*(2/3-t)*6
    return p
}
function hls_r(h,l,s,    q,p) { if(s==0)return l; q=(l<0.5)?l*(1+s):l+s-l*s; p=2*l-q; return _hue(p,q,h+1/3) }
function hls_g(h,l,s,    q,p) { if(s==0)return l; q=(l<0.5)?l*(1+s):l+s-l*s; p=2*l-q; return _hue(p,q,h)     }
function hls_b(h,l,s,    q,p) { if(s==0)return l; q=(l<0.5)?l*(1+s):l+s-l*s; p=2*l-q; return _hue(p,q,h-1/3) }

function clamp(v,lo,hi) { return (v<lo?lo:(v>hi?hi:v)) }
function to_hex(v)       { return sprintf("%02x", int(v*255 + 0.5)) }

function rgb2hex(r,g,b) { return "#" to_hex(r) to_hex(g) to_hex(b) }

# ---------------------------------------------------------------------------
# Boost functions
# ---------------------------------------------------------------------------
function boost_accent(hex,    r,g,b,h,l,s) {
    r=hex_r(hex); g=hex_g(hex); b=hex_b(hex)
    h=rgb_h(r,g,b); l=rgb_l(r,g,b); s=rgb_s(r,g,b)
    l = clamp(l, 0.50, 0.65)   # neon sweet spot — vivid but not washed out
    s = clamp(s + 0.35, 0, 1)  # push toward fully saturated
    return rgb2hex(hls_r(h,l,s), hls_g(h,l,s), hls_b(h,l,s))
}

function boost_white(hex,    r,g,b,h,l,s) {
    r=hex_r(hex); g=hex_g(hex); b=hex_b(hex)
    h=rgb_h(r,g,b); l=rgb_l(r,g,b); s=rgb_s(r,g,b)
    if (l < 0.80) l = 0.80     # ensure white roles are actually bright
    return rgb2hex(hls_r(h,l,s), hls_g(h,l,s), hls_b(h,l,s))
}

function boost_bg(hex,    r,g,b,h,l,s) {
    r=hex_r(hex); g=hex_g(hex); b=hex_b(hex)
    h=rgb_h(r,g,b); l=rgb_l(r,g,b); s=rgb_s(r,g,b)
    l = clamp(l, 0.08, 0.15)   # keep it dark enough to read text on
    s = clamp(s + 0.35, 0, 1)  # push saturation so the hue comes through
    return rgb2hex(hls_r(h,l,s), hls_g(h,l,s), hls_b(h,l,s))
}

# ---------------------------------------------------------------------------
# Setup key sets
# ---------------------------------------------------------------------------
BEGIN {
    n = split("color1 color2 color3 color4 color5 color6 color8 color9 color10 color11 color12 color13 color14 cursor", a)
    for (i = 1; i <= n; i++) accent[a[i]] = 1
    white["color7"]  = 1
    white["color15"] = 1
    bg["background"] = 1
}

# ---------------------------------------------------------------------------
# Process each line
# ---------------------------------------------------------------------------
{
    if (match($0, /#[0-9a-fA-F]{6}/)) {
        key    = $1
        color  = substr($0, RSTART, RLENGTH)
        prefix = substr($0, 1, RSTART - 1)
        suffix = substr($0, RSTART + RLENGTH)
        if (key in accent)     { print prefix boost_accent(color) suffix; next }
        if (key in white)      { print prefix boost_white(color)  suffix; next }
        if (key in bg)         { print prefix boost_bg(color)     suffix; next }
    }
    print $0
}
' "$KITTY_COLORS_FILE" > "${KITTY_COLORS_FILE}.tmp" \
    && mv "${KITTY_COLORS_FILE}.tmp" "$KITTY_COLORS_FILE"
